# Gunakan PHP image resmi berbasis Debian (ada apt-get)
FROM php:8.2-cli-bullseye

# Set working directory
WORKDIR /var/www

# Copy semua file project
COPY . .

# Install dependensi yang dibutuhkan
RUN apt-get update && apt-get install -y \
    zip unzip git curl libzip-dev libxml2-dev \
 && docker-php-ext-install zip pdo pdo_mysql \
 && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Install composer dependencies Laravel
RUN composer install --no-dev --optimize-autoloader
